### ISSUE TITLE
update events in event tab

### ISSUE THREAD

**Issue by rishhavv** [Repozo/dsc-jiit#1]
Orientation - 12/09/20
Node.js workshop - 13/09/20
Web-dev workshop - 26-27/09/20
30 days of google cloud - October 2020
ASPIRE - 6/12/2020
Mentorship programme launch - 03/01/2021

**Comment by akshatjain-akj** [comment]
#6  this pull request will fix above issue

**Comment by ssgshubham** [comment]
Issue completed, click [here](https://dsc-jiit-development-git-fork-ssgshubham-master.xatishayx.vercel.app/) to view the result.
